version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: parking-db
    environment:
      POSTGRES_DB: parking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - parking-net
  garage-sim:
    image: cfontes0estapar/garage-sim:1.0.0
    ports:
      - "3000:3000"

volumes:
  pgdata:

networks:
  parking-net:
    driver: bridge
