spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/parking
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

server:
  port: 3003

#logging:
#  level:
#    root: DEBUG